ALTER TABLE players 
ADD COLUMN street_name VARCHAR(255) NULL AFTER full_name,
ADD COLUMN age INT NULL AFTER dob,
ADD COLUMN shirt_number INT NULL AFTER age,
ADD COLUMN played INT DEFAULT 0,
ADD COLUMN clean_sheets INT DEFAULT 0,
ADD COLUMN goals INT DEFAULT 0,
ADD COLUMN image_url VARCHAR(512) NULL;
