ALTER TABLE players 
ADD COLUMN IF NOT EXISTS attribute_att INT DEFAULT 70,
ADD COLUMN IF NOT EXISTS attribute_tec INT DEFAULT 70,
ADD COLUMN IF NOT EXISTS attribute_tac INT DEFAULT 70,
ADD COLUMN IF NOT EXISTS attribute_def INT DEFAULT 70,
ADD COLUMN IF NOT EXISTS attribute_cre INT DEFAULT 70,
ADD COLUMN IF NOT EXISTS height_cm INT DEFAULT 178,
ADD COLUMN IF NOT EXISTS weight_kg INT DEFAULT 75,
ADD COLUMN IF NOT EXISTS preferred_foot VARCHAR(20) DEFAULT 'Right',
ADD COLUMN IF NOT EXISTS market_value DECIMAL(15,2) DEFAULT 0.00;
